# Site settings
title: "Rosdyana Kusuma's Blog"
header-img: "img/home-bg.jpg"
email: "rosdyana.kusuma@gmail.com"
description: "coding, eat, juve!!"
baseurl: ""
url: "http://rosdyana.github.io"
twitter_username: "rosdyana_kusuma"
github_username: "rosdyana"
facebook_username: "r3m1ck"
future: true

# sitemap
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Build settings
markdown: "kramdown"
highlighter: "rouge"
permalink: "pretty"
paginate: 10
timezone: "Asia/Taipei"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
gems: ["jekyll-paginate"]

kramdown:
  input: GFM
  syntax_highlighter: rouge
